### ISSUE TITLE
Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once

### ISSUE THREAD

**Issue by spectrenoir06** [TannerRogalsky/love.js#32] opened 2016-03-12 21:32 UTC
The game work in debug mode and release-compatibility but if open the page a second time have got this error

```
Error: [string "boot.lua"]:229: Already initialized
stack traceback:
    [C]: in function 'init'
    [string "boot.lua"]:229: in function <[string "boot.lua"]:223>
    [C]: in function 'xpcall'
Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.
Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.
Error: [string "boot.lua"]:229: Already initialized
stack traceback:
    [C]: in function 'init'
    [string "boot.lua"]:229: in function <[string "boot.lua"]:223>
    [C]: in function 'xpcall'
Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.
Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.
Uncaught abort("Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.") at Error
    at jsStackTrace (http://localhost:8000/love.js:1:17162)
    at stackTrace (http://localhost:8000/love.js:1:17345)
    at abort (http://localhost:8000/love.js:24:15936)
    at assert (http://localhost:8000/love.js:1:7547)
    at _emscripten_set_main_loop (http://localhost:8000/love.js:1:70494)
    at _emscripten_set_main_loop_arg (http://localhost:8000/love.js:1:281879)
    at Object.bl [as _main] (http://localhost:8000/love.js:6:1273)
    at Object.callMain (http://localhost:8000/love.js:24:14316)
    at Object.Module.setStatus (http://localhost:8000/:1288:22)
    at http://localhost:8000/love.js:24:15162
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
Uncaught abort("Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.") at Error
    at jsStackTrace (http://localhost:8000/love.js:1:17162)
    at stackTrace (http://localhost:8000/love.js:1:17345)
    at abort (http://localhost:8000/love.js:24:15936)
    at assert (http://localhost:8000/love.js:1:7547)
    at _emscripten_set_main_loop (http://localhost:8000/love.js:1:70494)
    at _emscripten_set_main_loop_arg (http://localhost:8000/love.js:1:281879)
    at Object.bl [as _main] (http://localhost:8000/love.js:6:1273)
    at Object.callMain (http://localhost:8000/love.js:24:14316)
    at Object.Module.setStatus (http://localhost:8000/:1288:22)
    at window.onerror (http://localhost:8000/:1304:16)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
'webkitMovementX' is deprecated. Please use 'movementX' instead.
'webkitMovementY' is deprecated. Please use 'movementY' instead.

```

**Comment by spectrenoir06** [comment] 2016-03-12 21:41
I'ts only appear in release-compatibility

**Comment by TannerRogalsky** [comment] 2016-03-13 00:14
@spectrenoir06 Can you give me a test case for this? And can you elaborate on what you mean by opening the page a second time?

**Comment by spectrenoir06** [comment] 2016-03-13 14:49
I try with this
```lua
function love.load()
	print("hello")
end
`````

first time this error

![capture d ecran de 2016-03-13 15 40 20](https://cloud.githubusercontent.com/assets/5509337/13729323/74093950-e932-11e5-9b34-eaf3ea14b23a.png)

second time working no error

third time and all the othertime same error than first time

if you add a love.update() and a love.draw() it make the error after one frame

**Comment by TannerRogalsky** [comment] 2016-03-13 16:30
I can't reproduce this. Can you try clearing your cache and trying again? Maybe you have some bad data hanging around somehow.

**Comment by spectrenoir06** [comment] 2016-03-13 16:41
i try in incognito mode it work the first time and second time but after the error reappear

1.  work  ( first time)
2.  work
3.  error
4.  error
5.  work
6.  error

I use Chromium version 48.0.2564.82 Ubuntu 15.04 (64-bit)

with the same code

````lua
function love.load()
    print("hello")
end
`````

**Comment by TannerRogalsky** [comment] 2016-03-13 16:45
I haven't test this on Linux much. I don't have a native install and graphics stuff runs slow in my VM. I'll look into this when I get a chance.

**Comment by spectrenoir06** [comment] 2016-03-13 17:27
I test with this code and i have 3 different behavior ( just  refreshing the page )

````lua
function love.load()
	print("load")
	i = 0
end

function love.update(dt)
 i = i + 1
 print("update", i)	 
end

function love.draw()
	print("draw", i)
	love.graphics.print(i, 10, 10)
end
```

![capture d ecran de 2016-03-13 18 20 38](https://cloud.githubusercontent.com/assets/5509337/13730196/00a9858e-e949-11e5-8e23-dabe00585714.png)
![capture d ecran de 2016-03-13 18 22 20](https://cloud.githubusercontent.com/assets/5509337/13730197/00aedbce-e949-11e5-94f5-78e03232db2b.png)
![capture d ecran de 2016-03-13 18 22 28](https://cloud.githubusercontent.com/assets/5509337/13730198/00b4b350-e949-11e5-8f5a-a043dc5282f1.png)

**Comment by DeejayArroba** [comment] 2016-03-29 18:38
I'm also having this issue (on ubuntu 15.10). Seems to happen randomly on chromium, but on firefox it works fine all the time.

**Comment by spectrenoir06** [comment] 2016-03-29 21:21
same on linux with google chrome Version 49.0.2623.108 (64-bit)

**Comment by wesleywerner** [comment] 2016-04-14 04:46
Thought I'd provide a better test case. I'd be happy to help out if extra steps are needed.

**Create a basic program**

```
angle = 0

function love.load (args)
  love.graphics.setBackgroundColor({128, 192, 64})
end

function love.update (dt)
  angle = (angle + dt) % 360
end

function love.draw ()
  love.graphics.setColor({64, 128, 192})
  love.graphics.circle("fill", 100, 150 + (math.sin(angle)*50), 50)
end

```

**Build** from the debug/ directory: `python ../emscripten/tools/file_packager.py game.data --preload /home/kbmonkey/coding/love/tests/basic@/ --js-output=game.js`

**Copy** `game.*` to `release-compatibility/` and `release-performance/`

**Run** `python -m SimpleHTTPServer` for each case.

## release-compatibility
1. Open a new Chrome browser in Incognito mode
2. Initial loads always seems to work
3. Refresh the page
4. Fails to load 8/10 times (sporadic)
5. Close the incognito window
6. Repeats from no 1

The fact that the first load from incognito seems to work indicates a caching issue in the chrome process. This seems to persist between browsing sessions in non-incognito mode, pointing again to a caching side-effect.

Iceweasel/Thunderbird does not exhibit this behaviour. 10/10.

## release-performance
1. Open a new Chrome browser in Incognito mode
2. Initial loads always seems to work
3. Refresh the page
4. No problems 10/10 times

## Error

```
Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.abort @ love.js:24assert @ love.js:1_emscripten_set_main_loop @ love.js:1_emscripten_set_main_loop_arg @ love.js:1bl @ love.js:6callMain @ love.js:24Module.setStatus @ (index):61(anonymous function) @ love.js:24
love.js:24 Uncaught abort("Assertion failed: emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.") at Error
    at jsStackTrace (http://localhost:8000/love.js:1:17162)
    at stackTrace (http://localhost:8000/love.js:1:17345)
    at abort (http://localhost:8000/love.js:24:15936)
    at assert (http://localhost:8000/love.js:1:7547)
    at _emscripten_set_main_loop (http://localhost:8000/love.js:1:70494)
    at _emscripten_set_main_loop_arg (http://localhost:8000/love.js:1:281879)
    at Object.bl [as _main] (http://localhost:8000/love.js:6:1273)
    at Object.callMain (http://localhost:8000/love.js:24:14316)
    at Object.Module.setStatus (http://localhost:8000/:61:20)
    at http://localhost:8000/love.js:24:15162
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.callMain @ love.js:24Module.setStatus @ (index):61(anonymous function) @ love.js:24

```

## System and Browser Versions

* Google Chrome 49.0.2623.110
* Mozilla Iceweasel 38.7.1
* Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29)

**Comment by TannerRogalsky** [comment] 2016-04-15 01:45
Wow! I appreciate the excellent error reporting, @wesleywerner! To be honest, I have no idea what is causing this but I've seen it on OSX as well (although I think it happens less frequently than on Linux). I will try to ask some emscripten devs if they have any insight.

Thanks, man!

**Comment by profan** [comment] 2017-05-06 21:16
Anything new here? Still in this swamp here as well!

**Comment by TannerRogalsky** [comment] 2017-05-30 20:50
I haven't seen this happen at all in 0.11. I think this is resolved by the new version.

**Closed by TannerRogalsky** 2017-05-30 20:50 UTC
Labels: bug, linux
